# Generated by Django 3.2.10 on 2022-06-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('Lastname', models.CharField(max_length=45, verbose_name='Apellido')),
                ('Cedula', models.IntegerField(max_length=10, verbose_name='Cédula')),
                ('Birthday', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Cellphone', models.IntegerField(max_length=10, verbose_name='Número de teléfono')),
            ],
        ),
    ]
