# Generated by Django 3.2.10 on 2022-06-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0002_rename_cellphone_users_cellphon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Cellphon',
            new_name='Cellphone',
        ),
    ]
