# Generated by Django 3.2.10 on 2022-06-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0006_alter_users_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Birthday',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
