# Generated by Django 3.2.10 on 2022-06-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0011_auto_20220625_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Birthday',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Cedula',
            field=models.BigIntegerField(verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Cellphone',
            field=models.BigIntegerField(verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
