# Generated by Django 3.2.10 on 2022-06-27 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0014_auto_20220626_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Cellphone',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Número de teléfono'),
        ),
    ]
