# Generated by Django 3.2.10 on 2022-06-25 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Cellphone',
            new_name='Cellphon',
        ),
    ]
