# Generated by Django 3.2.10 on 2022-06-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0003_rename_cellphon_users_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Cedula',
            field=models.BigIntegerField(verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Cellphone',
            field=models.BigIntegerField(verbose_name='Número de teléfono'),
        ),
    ]
