# Generated by Django 3.2.10 on 2022-06-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0004_auto_20220625_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Cedula',
            field=models.BigIntegerField(blank=True, verbose_name='Cédula'),
        ),
    ]
