# Generated by Django 3.2.10 on 2022-06-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0007_alter_users_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Cellphone',
            field=models.BigIntegerField(null=True, verbose_name='Número de teléfono'),
        ),
    ]
