# Generated by Django 3.2.10 on 2022-06-26 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0008_alter_users_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='Cedula',
            field=models.BigIntegerField(default=2, verbose_name='Cédula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='Cellphone',
            field=models.BigIntegerField(default=9, verbose_name='Número de teléfono'),
            preserve_default=False,
        ),
    ]
