# Generated by Django 3.2.10 on 2022-06-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0010_alter_users_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Birthday',
            field=models.DateField(default=None, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Cellphone',
            field=models.BigIntegerField(default=None, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Email'),
        ),
    ]
