# Generated by Django 3.2.10 on 2022-06-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0012_auto_20220625_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Birthday',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Cedula',
            field=models.BigIntegerField(null=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Cellphone',
            field=models.BigIntegerField(null=True, verbose_name='Número de teléfono'),
        ),
    ]
